#!/bin/bash
set -e

cd $(dirname $0)/..

: ${ARTIFACTS:=$(pwd)/assets}
: ${BUILD:=$(pwd)/build}

busybox_install()
{
    local conf=$1
    local bbconf=$2
    local target=$3

    mkdir -p ${BUILD}
    cd ${BUILD}

    local buildroot=$(ls -1 ${ARTIFACTS}/buildroot-*.tar.*)

    if [ ! -e "${buildroot}" ]; then
        echo "Failed to find busybox archive, found : ${buildroot}" 1>&2
        return 1
    else
        buildroot=$(basename $buildroot)
    fi

    DIR=${buildroot/.tar.*//}
    rm -rf ${DIR}
    mkdir -p ${DIR}
    tar xf ${ARTIFACTS}/${buildroot} -C ${DIR} --strip-components=1
    cd ${DIR}

    cp $conf .config
    if [ -n "$bbconf" ]; then
        cp $bbconf package/busybox/
    fi
    make oldconfig
    make

    tar cvJf $target -C output/images .
}

busybox_install "$1" "$2" "$3"
