#!/bin/bash
set -e

cd $(dirname $0)/..

: ${ARTIFACTS:=$(pwd)/assets}
: ${BUILD:=$(pwd)/build}

busybox_install()
{
    local build=$1
    local conf=$2
    local bbconf=$3
    local target=$4
    echo "SO $build, $conf, $bbconf, $target"
    echo "SO $target"

    mkdir -p ${BUILD}
    cd ${BUILD}

    local buildroot=$(ls -1 ${ARTIFACTS}/${TARBALL})

    if [ ! -e "${buildroot}" ]; then
        echo "Failed to find busybox archive, found : ${buildroot}" 1>&2
        return 1
    else
        buildroot=$(basename $buildroot)
    fi

    DIR=${buildroot/.tar.*//}
    mkdir -p ${DIR}
    tar xf ${ARTIFACTS}/${buildroot} -C ${DIR} --strip-components=1
    cd ${DIR}

    cp $conf .config
    if [ -n "$bbconf" ]; then
        cp $bbconf package/busybox/
    fi
    export HOME=${BUILD}
    make oldconfig
    cp .config ${target}.config
    if [ -n "$bbconf" ]; then
        cp package/busybox/$(basename $bbconf) ${target}.$(basename $bbconf)
    fi

    if [ "$build" == "build" ]; then
        make
        tar cvJf $target -C output/images .
    fi
}

busybox_install "$1" "$2" "$3" "$4"
