#!/bin/bash

cd $(dirname $0)/..

source scripts/build-common

apt-get install -y build-essential libncurses5-dev bc ccache

export CCACHE_DIR="${HOME}/.kernel-ccache"
export CC="ccache gcc"
export PATH="/usr/lib/ccache:$PATH"
KERNEL="$(cd ${ARTIFACTS}; echo linux-*.tar.*)"
DIR=${KERNEL/.tar.*//}

cd ${BUILD}

if [ ! -e ${DIR} ]; then
    echo Extracting ${ARTIFACTS}/linux-*.tar.*
    TEMP=$(mktemp -d -p ${BUILD})
    trap "rm -rf ${TEMP}" exit

    tar xf ${ARTIFACTS}/linux-*.tar.* -C $TEMP
    mv ${TEMP}/${DIR} ${DIR}
fi


cd ${DIR}
cp ${CONFIG}/kernel-config .config

make oldconfig
make -j$(nproc) tar-pkg

mkdir -p ${DIST}/kernel
mv linux*.tar ${DIST}/kernel
make headers_install INSTALL_HDR_PATH=${DIST}/kernel/headers
