#!/bin/bash
set -e

cd $(dirname $0)/..

DOCKER_IMAGE=${DOCKER_IMAGE:=rancher-os-base-build}

source scripts/build-common

run --assets ./scripts/build-common \
    ./scripts/bootstrap
run --assets ./config/kernel-config \
    ./scripts/build-kernel
run --assets ./config/busybox-config \
    ./scripts/build-busybox
run --assets ./config/busybox-config-static \
    ./scripts/build-busybox-static
run --assets ./scripts/install \
    ./scripts/package

finish
