#!/bin/bash
set -e

cd $(dirname $0)/..

: ${CONFIG:=$(pwd)/config}
: ${DIST:=$(pwd)/dist}
: ${ARCH:='arm x86_64'}

./scripts/download

for arch in $ARCH; do
  ./scripts/build-busybox ${CONFIG}/${arch}/buildroot-config ${CONFIG}/busybox-dynamic.config ${DIST}/${arch}
  ./scripts/package ${arch}
done
