#!/bin/bash
set -e

cd $(dirname $0)/..

DOCKER_IMAGE=${DOCKER_IMAGE:=rancher-os-base-build}

source scripts/build-common

run --assets ./scripts/build-common \
    ./scripts/bootstrap
run ./scripts/download
run --assets ./config/buildroot-config \
    --assets ./config/busybox-dynamic.config \
    --assets ./scripts/fix-up-image.sh \
    ./scripts/build-busybox
run ./scripts/package

finish
