#!/bin/bash

cd output/target
rm -rfv \
    usr/share/locale \
    usr/bin/cal \
    usr/bin/col \
    usr/bin/colcrt \
    usr/bin/colrm \
    usr/bin/column \
    usr/bin/findmnt \
    usr/bin/flock \
    usr/bin/i386 \
    usr/bin/ipcmk \
    usr/bin/isosize \
    usr/bin/look \
    usr/bin/lsblk \
    usr/bin/lscpu \
    usr/bin/lsipc \
    usr/bin/lslocks \
    usr/bin/lslogins \
    usr/bin/lsns \
    usr/bin/mcookie \
    usr/bin/namei \
    usr/bin/pg \
    usr/bin/prlimit \
    usr/bin/rev \
    usr/bin/script \
    usr/bin/scriptreplay \
    usr/bin/stat \
    usr/bin/tailf \
    usr/bin/uname26 \
    usr/bin/whereis \
    usr/bin/x86_64 \
    usr/sbin/blkdiscard \
    usr/sbin/blockdev \
    usr/sbin/cfdisk \
    usr/sbin/chcpu \
    usr/sbin/ctrlaltdel \
    usr/sbin/findfs \
    usr/sbin/fsfreeze \
    usr/sbin/ldattach \
    usr/sbin/mkfs \
    usr/sbin/rtcwake \
    usr/sbin/swaplabel \
    usr/sbin/wipefs \
    usr/share/bash-completion/completions/blkdiscard \
    usr/share/bash-completion/completions/blkid \
    usr/share/bash-completion/completions/blockdev \
    usr/share/bash-completion/completions/cal \
    usr/share/bash-completion/completions/cfdisk \
    usr/share/bash-completion/completions/chcpu \
    usr/share/bash-completion/completions/col \
    usr/share/bash-completion/completions/colcrt \
    usr/share/bash-completion/completions/colrm \
    usr/share/bash-completion/completions/column \
    usr/share/bash-completion/completions/ctrlaltdel \
    usr/share/bash-completion/completions/dmesg \
    usr/share/bash-completion/completions/fdisk \
    usr/share/bash-completion/completions/findmnt \
    usr/share/bash-completion/completions/flock \
    usr/share/bash-completion/completions/fsfreeze \
    usr/share/bash-completion/completions/fstrim \
    usr/share/bash-completion/completions/getopt \
    usr/share/bash-completion/completions/hexdump \
    usr/share/bash-completion/completions/ipcmk \
    usr/share/bash-completion/completions/ipcrm \
    usr/share/bash-completion/completions/ipcs \
    usr/share/bash-completion/completions/isosize \
    usr/share/bash-completion/completions/ldattach \
    usr/share/bash-completion/completions/logger \
    usr/share/bash-completion/completions/look \
    usr/share/bash-completion/completions/lsblk \
    usr/share/bash-completion/completions/lscpu \
    usr/share/bash-completion/completions/lsipc \
    usr/share/bash-completion/completions/lslocks \
    usr/share/bash-completion/completions/lslogins \
    usr/share/bash-completion/completions/lsns \
    usr/share/bash-completion/completions/mcookie \
    usr/share/bash-completion/completions/mkfs \
    usr/share/bash-completion/completions/mkswap \
    usr/share/bash-completion/completions/namei \
    usr/share/bash-completion/completions/pg \
    usr/share/bash-completion/completions/prlimit \
    usr/share/bash-completion/completions/readprofile \
    usr/share/bash-completion/completions/renice \
    usr/share/bash-completion/completions/rev \
    usr/share/bash-completion/completions/rtcwake \
    usr/share/bash-completion/completions/script \
    usr/share/bash-completion/completions/scriptreplay \
    usr/share/bash-completion/completions/setarch \
    usr/share/bash-completion/completions/setsid \
    usr/share/bash-completion/completions/swaplabel \
    usr/share/bash-completion/completions/swapoff \
    usr/share/bash-completion/completions/swapon \
    usr/share/bash-completion/completions/tailf \
    usr/share/bash-completion/completions/whereis \
    usr/share/bash-completion/completions/wipefs
