#!/bin/bash

cd $(dirname $0)/..
: ${ARTIFACTS:=$(pwd)/dist/artifacts}

./scripts/ci 2>&1 | tee build.log
mv build.log dist/

echo
echo "to publish release to github, run dist/publish.sh"

echo "#!/bin/sh"> dist/publish.sh
echo "github-release release --user rancher --repo os-base --tag v${VERSION} --pre-release" >> dist/publish.sh
echo "for f in \$(ls ./dist/artifacts) ; do" >> dist/publish.sh
echo "  github-release upload  --user rancher --repo os-base --tag v${VERSION} --file ./dist/artifacts/\${f} --name \${f}" >> dist/publish.sh
echo "done" >> dist/publish.sh
echo "github-release upload  --user rancher --repo os-base --tag v${VERSION} --file release.log --name release.log" >> dist/publish.sh

chmod 755 dist/publish.sh
