#!/bin/bash

cd $(dirname $0)/..
: ${ARTIFACTS:=$(pwd)/dist/artifacts}

./scripts/ci 2>&1 | tee build.log
mv build.log dist/

COMMIT=$(git rev-parse --short HEAD)

echo
echo "to publish release to github, run dist/publish.sh"

echo "#!/bin/sh"> dist/publish.sh
echo "hub release create -t ${COMMIT} -m ${VERSION} ${VERSION}" >> dist/publish.sh
echo "for f in \$(ls ./dist/artifacts) ; do" >> dist/publish.sh
echo "   hub release edit -m ${VERSION} -a ./dist/artifacts/\${f} ${VERSION}" >> dist/publish.sh
echo "done" >> dist/publish.sh
echo "hub release edit -m ${VERSION} -a ./dist/build.log ${VERSION}" >> dist/publish.sh

chmod 755 dist/publish.sh
